config/routes.rb
Rails.application.routes.draw do
  # Switch root to the view we want.
  root "todo_lists#index"

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.nil?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action :set_todo_list
    before_action :set_todo_item, except: [:create]

    def create
        @todo_item = @todo_list.todo_items.create(todo_item_params)
        redirect_to @todo_list
    end

    def destroy
        @todo_item = @todo_list.todo_items.find(params[:id])
        if @todo_item.destroy
            flash[:success] = "Todo Item has been deleted successfully."
        else
            flash[:error] = "Todo Item can not be deleted. Try later."
        end
        redirect_to @todo_list
    end

    def complete
        @todo_item.update_attribute(:completed_at, Time.now)
        redirect_to @todo_list, notice: "Todo item completed"
    end
        
    private
    
    def set_todo_list
        @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
        @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def todo_item_params
        params[:todo_item].permit(:content)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWebpackExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content-wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
    <div class="form-add-item">
        <%= f.text_field :content, placeholder: "New ToDo", class: "form-control" %>
        <%= f.submit "Create a new Item", class: 'form-control btn btn-md btn-success' %>
    </div>
<%- end -%>

app/views/todo_lists/_form.html.erb
<%= form_for(todo_list) do |f| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="field">
    <legend><h6><%= :title %></h6></legend>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="field">
    <legend><h6><%= :description %></h6></legend>
    <%= f.text_area :description, class: "form-control" %>
  </fieldset>

  <fieldset class="actions">
    <%= f.submit "Create", class: "form-control btn btn-submit btn-primary" %>
  </fieldset>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="btn-group mb-5">
    <%= link_to 'Back', todo_lists_path, class:"btn btn-md btn-outline-danger" %>
    <%= link_to 'Show', @todo_list, class:"btn btn-md btn-outline-warning" %>
</div>
<h1>Editing Todo List</h1>
<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page">
  <div class="page-header text-center">
    <h1>Todo Lists</h1>
  </div>
  
  <!-- Card View -->
  <legend>Card View</legend>
  <div class="page-body">
    <% @todo_lists.each do |todo_list| %>
      <div class="card" style="width: 18rem;">
        <%= image_tag "TodoList.svg", class: "card-img-top img-page-referrer" %>
        <div class="card-body">
          <h5 class="card-title"><%= todo_list.title %></h5>
          <p class="card-text"><%= truncate(todo_list.description, length: 100) %></p>
        </div>
        <div class="card-footer text-center">
          <%= link_to todo_list, class:"btn btn-outline-primary btn-sm card-link" do %>
            <i class="fa fa-eye fa-2x text-primary"></i>
          <% end %>
          <%= link_to edit_todo_list_path(todo_list), class:"btn btn-outline-info btn-sm card-link" do %>
            <i class="fa fa-pencil-alt fa-2x text-info"></i>
          <% end %>
          <%= link_to todo_list, method: :delete,
                              class:"btn btn-outline-danger btn-sm card-link",
                              data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <hr />

  <!-- Table View -->
  <legend>Table View</legend>
  <div class="page-body-table">
    <table id="example" class="display" style="width:100%">
      <thead>
          <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Description</th>
          </tr>
      </thead>
      <tbody>
        <% @todo_lists.each do |todo_list| %>
          <tr>
              <td><%= todo_list.id %></td>
              <td><%= todo_list.title %></td>
              <td><%= truncate(todo_list.description, length: 100) %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
          <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Description</th>
          </tr>
      </tfoot>
    </table>
  </div>

  <div class="page-footer">
    <div class="text-center mt-5">
      <%= link_to new_todo_list_path, class: "btn btn-lg btn-float-right btn-success text-white" do %>
        <i class="fa fa-plus fa-2x"></i>
      <% end %>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
  } );
</script>

app/views/todo_lists/new.html.erb
<div class="mb-5">
    <%= link_to 'Back', todo_lists_path, class: "btn btn-md btn-outline-warning" %>
</div>

<legend>
    <h1>New Todo List</h1>
</legend>

<div class="mt-5">
    <%= render 'form', todo_list: @todo_list %>
</div>

app/views/todo_lists/show.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark">
  <div class="container">
    <div class="navbar-brand">
      <h1><%= @todo_list.title %></h1>
    </div>
    <div class="navbar navbar-nav" id="navigate">
      <div class="btn-group">
        <%= link_to 'Back', todo_lists_path, class: "btn btn-outline-warning text-white" %>
        <%= link_to 'Edit', edit_todo_list_path(@todo_list), class: "btn btn-outline-warning" %>
      </div>
    </div>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="container">
    <h4 class="text-muted">Description:</h4>
    <p><%= @todo_list.description %></p>
  </div>
</div>

<hr/>

<div class="container">
  <div class="row">
    <div class="todo_items_wrapper"> 
      <ul class="list-group list-group-flush">
        <% @todo_list.todo_items.each do |todo_item| %>
          <li class="list-group-item">
            <div class="todos">
              <p class="<%= todo_item.completed? ? 'item_completed' : 'item' %>"><%= todo_item.content %></p>
              <ul class="list-unstyled">
                <li>
                  <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
                    <button class="btn btn-sm">
                      <i class="fa <%= todo_item.completed? ? 'fa-check-square':'fa-square-full'%> text-primary"></i>
                    </button>
                  <% end %>
                </li>
                <li>
                  <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id),
                              method: :delete, data: { confirm: "Are you sure?" } do %>
                              <button class="btn btn-sm"><i class="fa fa-times text-danger"></i></button>
                  <% end %>
                </li>
              </ul>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="new-item-form">
      <%= render "todo_items/form" %>
    </div>
  </div>
</div>